channels:
- defaults
- conda-forge

dependencies:
- requests
- astropy
- astropy-healpix
- regions
- matplotlib
- jupyter
- pip:
  - git+https://github.com/astropy/astroquery.git
  - mocpy
  - ipyaladin
  - spherical-geometry
