channels:
- defaults
- conda-forge
- tboch


dependencies:
- requests
- astropy
- astropy-healpix
- regions
- matplotlib
- jupyter
- ipywidgets
- ipyaladin
- pip:
  - git+https://github.com/astropy/astroquery.git
  - mocpy
  - spherical-geometry
